# Generated by Django 6.0.6 on 2026-07-02 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'github_url'), name='unique_repository_per_user'),
        ),
    ]
